# @package _group_
name: "dreamer"

agent:
  _target_: mbrl.planning.DreamerAgent
  planning_horizon: ${overrides.planning_horizon}
  optimizer_cfg: ${action_optimizer}
  verbose: ${debug_mode}

num_initial_trajectories: 5
action_noise_std: 0.3
test_frequency: 25
num_episodes: 1000
dataset_size: 1000000